title: NSSPC lecture notes
description: NSSPC lecture notes
theme: just-the-docs

url: https://samuelabc.github.io
color_scheme: dark

aux_links:
  Source Repository: https://github.com/samuelabc/nsspc-lectures
